cabal-version: 3.0
name:          dep
version:       1.0
build-type:    Simple
data-files:    data/*.txt

library
  exposed-modules:  Dep
  other-modules:    Paths_dep
  hs-source-dirs:   src
  build-depends:    base
  cmm-sources:      cmm/Dep.cmm
  asm-sources:      asm/Dep.S
  asm-options:      -DASM
  default-language: Haskell2010

-- Neither of these is in the build plan, as benchmarks are not enabled.
library bench-lib
  visibility:       private
  exposed-modules:  Dep
  hs-source-dirs:   src
  build-depends:    base
  js-sources:       js/x.js
  default-language: Haskell2010

benchmark bench
  type:             exitcode-stdio-1.0
  main-is:          Bench.hs
  hs-source-dirs:   bench
  build-depends:    base, dep:bench-lib
  default-language: Haskell2010
